### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by rbavery** [CNES/Start-MAJA#1]
Hello and thanks for the great work on this algorithm. I'm interested in adapting MAJA's time series based method for cloud detection to Planet Labs imagery and was curious if there are plans to make the source code available?

**Comment by olivierhagolle** [comment]
Hi, sorry for replying late.

MAJA is not yet open source, but I intend to file it again to CNES authorities, in order to release the code. I am not sure it will succeed but I hope so.
Anyway, it will take a while.
Best regards,
Olivier

**Comment by rbavery** [comment]
I appreciate the advocacy!
