### ISSUE TITLE
download_CAMS.py error Visiting database marser : expected 660, got 630

### ISSUE THREAD

**Issue by deangelo** [CNES/Start-MAJA#11]
While trying to download the monthly CAMS data with the following command and my unprivileged account, I got an error (from ECMWF library). Does that mean I need a privileged account?

$ ./download_CAMS.py -d 20150601 -f 20190430 -k -w /data/PBA_gluster/projects/MAJA/CAMS/write -s ncks -k -a /data/PBA_gluster/projects/MAJA/CAMS/DBL

mars - INFO   - 20190507.153712 - Maximum retrieval size is 30.00 G
retrieve,stream=oper,levelist=1/2/3/5/7/10/20/30/50/70/100/150/200/250/300/400/500/600/700/850/925/1000,area=g,levtype=pl,expver=0001,padding=0,step=0,grid=1.25/1.25,param=157.128,time=00,date=20150601/to/201506
30,type=fc,class=mcmars - INFO   - 20190507.153712 - Automatic split by date is on

mars - INFO   - 20190507.153712 - Processing request 1

RETRIEVE,
    CLASS      = MC,
    TYPE       = FC,
    STREAM     = OPER,
    EXPVER     = 0001,
    REPRES     = SH,
    LEVTYPE    = PL,
    LEVELIST   = 1/2/3/5/7/10/20/30/50/70/100/150/200/250/300/400/500/600/700/850/925/1000,
    PARAM      = 157.128,
    TIME       = 0000,
    STEP       = 0,
    DOMAIN     = G,
    RESOL      = AUTO,
    GRID       = 1.25/1.25,
    PADDING    = 0,
    DATE       = 20150601/20150602/20150603/20150604/20150605/20150606/20150607/20150608/20150609/20150610/20150611/20150612/20150613/20150614/20150615/20150616/20150617/20150618/20150619/20150620/20150621/20150
622/20150623/20150624/20150625/20150626/20150627/20150628/20150629/20150630

mars - INFO   - 20190507.153712 - Web API request id: 5cd1a5a2a2de1951c1982e58
mars - INFO   - 20190507.153712 - Requesting 660 fields
mars - INFO   - 20190507.153712 - Calling mars on 'marser', callback on 55669
2019-05-07 17:37:23 Request is active
mars - INFO   - 20190507.171224 - Server task is 65 [marser]
mars - INFO   - 20190507.171225 - Request cost: 630 fields, 79.6813 Mbytes on 2 tapes, nodes: hpss [marser]
mars - INFO   - 20190507.173430 - Transfering 83551860 bytes
mars - WARN   - 20190507.173446 - Visiting database marser : expected 660, got 630
mars - INFO   - 20190507.173446 - 630 fields have been interpolated
mars - ERROR  - 20190507.173446 - Expected 660, got 630.
mars - ERROR  - 20190507.173446 - Request failed
...

**Comment by olivierhagolle** [comment]
Hi Pablo,
I think this product was not existing in 2015, and started end of january 2017, so you should start in Feburary. To download CAMS before that, it is necessary to use different settings, I will have to change the download module to allow that.
Olivier

**Comment by deangelo** [comment]
Hi Olivier,
thanks, I'll try to download the data from Feb. 2017 onwards first.
Pablo
