### ISSUE TITLE
Prevent L1C product in analyze

### ISSUE THREAD

**Issue by denizmenekay** [CNES/Start-MAJA#22]
Hello!
I want to do cloud masking of L2A product by using maja. So I dont need to use L1C product, but when I work the program, it tells me error which is "Start-Maja - ERROR - No L1C product found in ...(directory)". Is it possible to ignore that?

**Comment by olivierhagolle** [comment]
Hi 
it MAJA does not find any L1C in the input directory, then it cannot process them. Please check why it is not finding it. If you do not find why, please provide the content of your folders.txt file, the command line you used, and the log returned by MAJA (as I told you already twice on other channels).
Regards,
Olivier

**Comment by denizmenekay** [comment]
I just tought that either one of the product (L2A or L1C) will be enough to work it. I am downloading specific images from sentinel hub. I will then try it one more time by using L1C and L2A products together. If I got error in that case, I can share the last situation of my folders. Thank you and regards.

**Comment by olivierhagolle** [comment]
Hi Deniz,
I do not understand what you are trying to do, and I am not sure you understand what MAJA is, and clearly you did not read or understand the docs provided. 
MAJA is a tool to generate good quality L2A, so it needs L1C as input, and it is a multi-temporal processor, so it needs a time series of L1C, not just one. 
The question is, do you really need MAJA ?
Olivier

**Comment by denizmenekay** [comment]
Oh, thank you for your warning. Let me explain my aim maybe you are right. I have some L2A cloudy pictures (downloaded from sentinel hub) and need to make cloud masking. I am planning to do that with different programs, then compare and see which program gives a better result. I thought that MAJA is a program that analyse and make cloud masking of L2A pictures. Am I wrong? I also got inspiration from your article "Validation of Copernicus Sentinel-2 Cloud Masks Obtained from MAJA, Sen2Cor, and FMask Processors Using Reference Cloud Masks Generated with a Supervised Active Learning Procedure"

**Comment by olivierhagolle** [comment]
MAJA is a L2A processor, it makes L2A products using different methods than those of ESA or others.  
The L2A contains a cloud mask and provides surface reflectances. The main feature is that MAJA uses the time dimension to do that. Please read the readme, follow the links to other explanations, and you'll know everything about it ;)

**Comment by denizmenekay** [comment]
Hello again :)

I unfortunately still can't work the program and don't know where the mistake is. If you have a working example, is it possible for you to show me or send? That may be good for me to compare and see the missing points.
