### ISSUE TITLE
GIPP AUX_REFDE2 problems

### ISSUE THREAD

**Issue by xurui96125** [CNES/Start-MAJA#28]
I am trying to run MAJA 3.3.0 without CAMS data for the test region around RIO, but am blocked by the following :
![Screenshot from 2019-07-26 21-27-49](https://user-images.githubusercontent.com/49867834/61955451-a0b77b80-afed-11e9-9e6a-528cb4eab1a3.png)
[S2A_MSIL1C_20160802T130252_N0204_R095_T23KPQ_20160802T130656.SAFE.log](https://github.com/CNES/Start-MAJA/files/3435999/S2A_MSIL1C_20160802T130252_N0204_R095_T23KPQ_20160802T130656.SAFE.log)

The GIPP directory used is GIPP_S2_MAJA_3.3_TM,downloaded from http://tully.ups-tlse.fr/olivier/gipp_maja/tree/master/GIPP_S2_MAJA_3.3_TM.The GIPP file was in the directory of start-maja.py .Here is the folder.txt that I configure:
[folders.txt](https://github.com/CNES/Start-MAJA/files/3435979/folders.txt)

Can you help me? I really need your help. Thank you!

**Comment by jerome-colin** [comment]
Dear Xu Rui,
According to the screenshot, it seems like you point to GIPP with CAMS, not without ("../GIPP_S2AS2B_CAMS"). Did you renamed and/or modified the GIPP folders ? Are you pointing to the content of "GIPP_S2_MAJA_3.3_TM" ?
Please attach your log file to your answer.
Thanks,
Jerome

**Comment by xurui96125** [comment]
Hi Jerome,
Thank you for your reply.Last time,I renamed the GIPP_S2_MAJA_3.3_TM folders as GIPP_S2AS2B_CAMS.But this time ,I did not rename the GIPP_S2_MAJA_3.3_TM folders,the same problem was arised, 
![GIPP_problem](https://user-images.githubusercontent.com/49867834/62374872-80e50200-b56f-11e9-8ac6-edb64a30810d.png)
The fellowing is my log file and folders.txt :
[S2A_MSIL1C_20160802T130252_N0204_R095_T23KPQ_20160802T130656.SAFE.log](https://github.com/CNES/Start-MAJA/files/3461515/S2A_MSIL1C_20160802T130252_N0204_R095_T23KPQ_20160802T130656.SAFE.log)
[folders.txt](https://github.com/CNES/Start-MAJA/files/3461521/folders.txt)
Thanks ,
Xu Rui

**Comment by olivierhagolle** [comment]
Hi Xu Rui,
Sorry for replying late, that's an holiday period, here.
the message you get is related to the absence of a DTM (" AUX_REFDE2"). 
- did you make it (with TMPCreation) for your specific tile 23KPQ ?
- did you follow the instructions regarding the DTM ?

Best regards,
Olivier

**Comment by Mholst03** [comment]
Hi there,

I am also trying to run MAJA 3.3.0 without CAMS data for a test area around Kolding, Denmark (tile 32UNG).

I have 5 L1C files, I have downloaded the SRTM and SWBD files as explained in the tutorial provided on github. I have created the DTM required with the "DTMCreation-tool" using a L1 product from [the Start-MAJA github tutorial](https://github.com/CNES/Start-MAJA/tree/master/prepare_dtm#dtmcreation-tool-using-a-l1-product).

I have the same error as the one described here. 

See below my folders.txt and log files :
[folders.txt](https://github.com/CNES/Start-MAJA/files/3515513/folders.txt)
[S2A_MSIL1C_20190609T103021_N0207_R108_T32UNG_20190609T124633.SAFE.log](https://github.com/CNES/Start-MAJA/files/3515510/S2A_MSIL1C_20190609T103021_N0207_R108_T32UNG_20190609T124633.SAFE.log)

I hope you'll be able to help me,
Best regards,
Marion

**Comment by olivierhagolle** [comment]
Hi Marion,
We are developing a new version of Start_MAJA, as several users have difficulties, I hope it will improve soon.

The "AUX_REFDE"2 file is the DTM. The DTM should be stored in 
repCode+"/DTM/, where repCode=/media/mhadmin/OS/Start-MAJA in your case.

Could you please list the contents of this folder anc check it contains a DTM folder, with the DTM folder for 32UNG in it  ?

Thanks,
Olivier

**Comment by Mholst03** [comment]
Hi Olivier, 

Thank you for your quick response.

Content of the repostiory "repCode=/media/mhadmin/OS/Start-MAJA":
cams_download
LICENSE
SRTM
Common
LUT_MAJA_S2A_S2B_CAMS_H2ONew_20190410.tgz
start_maja.py
DTM
LUT_S2AS2B
userconf
folders.txt
prepare_dtm
Water
GIPP_S2_MAJA_3.3_TM
Readme.md

In the DTM folder there is a folder called 32UNG, and inside a folder called "S2__TEST_AUX_REFDE2_T32UNG_0001". In this one there are a folder called "S2__TEST_AUX_REFDE2_T32UNG_0001.DBL.DIR", and a file: S2__TEST_AUX_REFDE2_T32UNG_0001.HDR

Best regards,
Marion

**Comment by olivierhagolle** [comment]
Thanks for the detailed content
S2__TEST_AUX_REFDE2_T32UNG_0001 should be directly in the DTM folder, and 32UNG folder should be removed. 
I hope it will solve the issue, please tell us !
Olivier

**Comment by Mholst03** [comment]
Hi Olivier,

I have put S2__TEST_AUX_REFDE2_T32UNG_0001in the DTM folder, removed 32UNG folder and it ran!

Thanks!
Marion

**Comment by olivierhagolle** [comment]
Good news !
I am closing the issue (having no news from @xurui96125 )
Please feel free to reopen it.
Olivier

**Comment by xurui96125** [comment]
Thank you very much. Under your guidance, I have successfully run MAJA.

At 2019-08-20 17:47:52, "Olivier Hagolle" <notifications@github.com> wrote:


Good news !
I am closing the issue (having no news from @xurui96125
Please feel free to reopen it.
Olivier
