### ISSUE TITLE
Is it possible to run processing in nominal mode strictly without backward ?

### ISSUE THREAD

**Issue by geometrika** [CNES/Start-MAJA#31]
subj

**Comment by olivierhagolle** [comment]
Well, that's a blunt style of message ;)

MAJA is a recurrent algorithm (iteration n needs iteration n-1 as input), that you need to initialise somehow.  So there are two initialisation modes proposed, Init mode, and backward mode. 

The quality with backward mode is much better, and start MAJA only uses backward mode.
Within Start_MAJA, you still could change the number of images to use in the backward mode, but it is hardcoded (shame on me) It is almost the last line of Start-MAJA
`nb_backward = 8`

You can reduce this number to 1 or  2 (I am not fully sure it works with 1), but it will definitely degrade the data quality.

I am curious about  why you would need to skip the backward mode, in more than a word ;)
Best regards,
Olivier

**Comment by geometrika** [comment]
Hi, Olivier and thank you for explanations!
I think it's me who is a little bit blunt not only message...  

I'll try to explain my case but I'm not sure it is relevant.  

I need input data for crop mask, crop type classification algorithm (now we try sen2agri ready to go L4 proccessors and in future may be something coded by ourselves). I see that on one side, calculation of L2A from L1C is very tough computational operation on the other side Sentinel 2 L2A products with cloud-shadow masks are provided on SciHUB and Amazon.  
So I'm interested in testing sen2agri with input data quality like L2A from SciHUB.

**Comment by olivierhagolle** [comment]
Thanks for the describing your use case ! I  was above all wondering why you would like to use MAJA without backward mode ?

MAJA is computationally intense, but it pays off with the quality of products
Olivier

**Comment by geometrika** [comment]
Olivier,
may I ask you if it's appropriate, may be you are aware of it - what particular path (file or dir) from output MAJA (3.3.0) should be put into "-input" parameter to run CropMaskFused.py  script (run L4a proccessor of sen2agri in manual mode) ?

**Comment by olivierhagolle** [comment]
Hi, 
you should ask that in the sen2agri Forum, here, we can't answer
https://github.com/Sen2Agri/Sen2Agri-System
Olivier

**Comment by geometrika** [comment]
Ok!
