### ISSUE TITLE
error - no GIPP input data matching with the 'AUX_REFDE2' File_Type pattern

### ISSUE THREAD

**Issue by lefebvre-antoine** [CNES/Start-MAJA#32]
Dear Olivier,

I'm trying to process L1C images from peps but I have the error below :
`PreProcessing: vns::Data::ERROR: DataApplicationHandler(0x1ec97f0): In the input directory, there is no GIPP input data matching with the 'AUX_REFDE2' File_Type pattern! [vnsDataApplicationHandler.cxx:1699] [MAJA Data Exception]  [vnsMajaMainProcessor.cxx:main:129]`

May we miss something during the setup of MAJA ?

Thank you very much !
Antoine Lefebvre

**Comment by olivierhagolle** [comment]
Bonjour Antoine
Solved here, I think :
https://github.com/CNES/Start-MAJA/issues/28
(*AUX_REFDE* files should be directly in the DTM folder)
Olivier

**Comment by lefebvre-antoine** [comment]
it works! Thanks!
