### ISSUE TITLE
ECMWFT data provided by Sentinel-2

### ISSUE THREAD

**Issue by glennie** [CNES/Start-MAJA#34]
Hello,
We have noticed a file AUX_ECMWFT in GRANULE/L1C_T31TDM_A012947_20190829T105030/AUX_DATA within the zip file of a sentinel-2 sat image.
Is there a way to use this file's data as cam data?
Thanks and regards

**Comment by olivierhagolle** [comment]
Hi, 
this file does not contain the CAMS information, as far as I know.
Olivier

**Comment by glennie** [comment]
Hello,
OK. Thx.
Kind regards,
