### ISSUE TITLE
maja in sen2agri

### ISSUE THREAD

**Issue by smfcrts** [CNES/Start-MAJA#35]
Hello,
I updated sen2agri platform to 2.0.1, but maja doesn't process l2a product.The log file are attached 
[demmaccs.log](https://github.com/CNES/Start-MAJA/files/3728631/demmaccs.log)
[demmaccs_29SNR.log](https://github.com/CNES/Start-MAJA/files/3728632/demmaccs_29SNR.log)
When i run demmaccs manually, it gives Error while copying the filename <OUT_DIR/share/config/Templates/PMC_LxREPT.EEF> to </mnt/archive/maccs_def/morocco/l2a/S2B_MSIL2A_20191007T112119_N0208_R037_T29SNR_20191007T140832.SAFE/maccs_29SNR/PMC_LxREPT.EEF> !  [vnsSystem.cxx:CopyFile:406]
where outdir is /opt/MAJA/
Note that  /opt/MAJA/ has a full right access. When i installed maja in /home/ and i run the command it gives:
File "/usr/share/sen2agri/sen2agri-demmaccs/demmaccs.py", line 552, in <module>
    out = maccs_launcher(demmaccs_contexts[0])
  File "/usr/share/sen2agri/sen2agri-demmaccs/demmaccs.py", line 331, in maccs_launcher
    if run_command(cmd_array, demmaccs_context.output, tile_log_filename) != 0:
  File "/usr/lib/python2.7/site-packages/sen2agri_common_db.py", line 155, in run_command
    res = subprocess.call(cmd_array, shell=False)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
What might cause this error?Should maja be installed in opt or in another folder?

**Comment by olivierhagolle** [comment]
Hi, 
We can't answer for sen2agri, you should open this issue in the sen2Agri repository
https://github.com/Sen2Agri/Sen2Agri-System
Regards
Olivier

**Comment by smfcrts** [comment]
Thank you for your reply

Le mer. 16 oct. 2019 à 16:48, Olivier Hagolle <notifications@github.com> a
écrit :
