### ISSUE TITLE
Error while loading EEF file.

### ISSUE THREAD

**Issue by Slavko12345** [CNES/Start-MAJA#36]
Hi!

I am trying to run MAJA (v.3.3.2) without CAMS option on L1C tiles downloaded from peps.
At the moment I am getting such error: 
vns::Data::ERROR: EarthExplorerXMLFileHandler(0x7af7d0): XMLFileHandler::LoadFile: Error while loading the file [.../Start-MAJA/temp_files/T22KHB/22KHB/GIPP_united/in/S2A_TEST_GIP_L2COMM_L_ALLSITES_00001_20190626_21000101.EEF]. Parsed with errors.

Will be grateful for any ideas or suggestions.

**Comment by olivierhagolle** [comment]
Hi Slavko,

we have had issues with products that did not include the full information requested by MAJA, regarding viewing angles for instance, but it was with early S2 products.

Does it happen for each product you process, or just for this specific one ?
Could you please provide us the command line, log printed on the screen, and log file of the product for which the error is observed ? 
Thanks in advance,
Olivier

**Comment by Slavko12345** [comment]
I tried different dates for the same tile - it resulted in the same error.
By the way, I found that I can use another tile for which 2A data is available, so at the moment I will close the issue.
By the way, thank you for the development and continuous support of the project - it is great!

**Comment by olivierhagolle** [comment]
Hey, don't give up.
there was an error in the xml file (a missing bracket '<' in the xml)
If you download the GIPP files again, this error should not happen anymore.
Olivier

**Comment by Slavko12345** [comment]
In fact, 4 L2COMM GIPP files for Sentinel2-TM in the repository also have the same bug (at line 111, absence of '<'), after fixing that it started working!
Thank you for pointing that out!

**Comment by olivierhagolle** [comment]
I did the correction too quickly, I must have forgotten to push the file, sorry.
Glad it works !
I will be happy to get feedback
Olivier

**Comment by Slavko12345** [comment]
At the moment I run the script without CAMS option and compared result with neighboring tile for which 2A data was available (at the same day). It looks similar, but there is some color difference (probably because of CAMS). So in the nearest future I will probably run it with CAMS and give more feedback.
Thanks again!

**Comment by olivierhagolle** [comment]
Hi Slavko, 
Theia is not running with CAMS option either (as ECMWF changed the CAMS format in July and our adaptation is not fully ready yet). The colour difference you seem to have observed probably lies in the residual inaccuracy of MAJA, given that the tiles are processed independently (and although MAJA should have lower residuals than usually observed with Sen2cor).
Best regards,
Olivier

**Comment by Slavko12345** [comment]
Ok, thanks for the info!
I have one more stupid question.
Let's say I want to use WASP for L2A->L3A conversion.
Is there any way to use it on L2A data from scihub.copernicus (2A data is available there, but it has a different format)? 
Maybe, there is a way to convert one format to another, or there are some missing parts in copernicus format?
Maybe, the only way is to convert 1C data to 2A using MAJA first?
Thank you again!

**Comment by olivierhagolle** [comment]
Hi Slavko, 
we did not write an interface to Sentinel-2 L2A from ESA. We could imagine it, but WASP is not adapted to Sen2cor (the processor behind ESA's L2A). WASP requires a very good cloud mask, and, well, Sen2cor cloud masks are not good enough, and would result in data gaps, and artefacts
Olivier
