### ISSUE TITLE
Configuration files missing?

### ISSUE THREAD

**Issue by Greforb** [CNES/Start-MAJA#4]
In the readme you mention that you can get the parameters folder in a version using CAMS and one not using CAMS and that the one using CAMS is rather big. When you click the link to the one NOT using CAMS: http://tully.ups-tlse.fr/olivier/gipp_maja/tree/master/GIPP_MAJA_3.1.2_TM and reads the readme, you are told that "For data volume reasons, the directory is not complete, and you should add the files contained in this reference". When you follow that link you end up at: https://zenodo.org/record/2553164 which seems to be the LUTs for the version WITH CAMS? It seems to be the same (although an older version) LUTs you get when picking configuration for the version actually using CAMS. When you unpack the data you get from https://zenodo.org/record/2553164 you get the GIPP_MAJA_3.1.2_TM_CAMS folder. It's not clear (1) if I can use that for the version running without CAMS and (2) if this is the complete configuration dir or I have to copy its content into my configuration folder which I got from: http://tully.ups-tlse.fr/olivier/gipp_maja/tree/master/GIPP_MAJA_3.1.2_TM?

**Comment by olivierhagolle** [comment]
Hi, 
I will try to improve the documentation, but yes, I have put all the LUT files in one single package. If you do not use the CAMS option, the only drawback is that 90% of the files are not useful. The differences in parameters relies on the files in the git repository.
By the way, we found a bug and do not advise to activate the CAMS option so far.
Best regards,
Olivier

**Comment by Greforb** [comment]
Ok, I have just copied the CAMS folders into my non-CAMS configuration folder that I downloaded from http://tully.ups-tlse.fr/olivier/gipp_maja/tree/master/GIPP_MAJA_3.1.2_TM . They're probably not used then, but it doesn't matter or? Because of you're advise I do not wish to use CAMS at the moment.

**Comment by olivierhagolle** [comment]
Yes, it does not matter (except for disk space)
Olivier
