### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by saberioon** [CNES/Start-MAJA#48]
When I'm trying to install MAJA 3.3.2_TM on my openSUSE Leap 15.1 I received this error 

 `Verifying archive integrity...  100%  Error in MD5 checksums: d41d8cd98f00b204e9800998ecf8427e is different from 132ddb47e68a365ea7e12b8c837a71e9`

I'm not sure, what cause this error, but a quick search suggests that the bash file is corrupted ! 

Do you have any suggestion, How to fix it ?

**Comment by petket-5** [comment]
Hi,

Did you try downloading the archive again?

Kind regards,
Peter

**Comment by saberioon** [comment]
Yes, I have tried two times, but gave me the same error

**Comment by petket-5** [comment]
This error does not seem to be related to maja itself, but rather the packaging mechanism.
On top I don't have an openSUSE machine around here.

We are using makeself to create the .run file.
You can find some help here: https://github.com/megastep/makeself

**Comment by sac3g15** [comment]
@saberioon Did you manage to fix this issue?
