### ISSUE TITLE
Maja processing does not include images for 2020

### ISSUE THREAD

**Issue by intiluna** [CNES/Start-MAJA#56]
Platform and sofware versions:
• Ubuntu 18.04.4 LTS
• Python 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
• GDAL 2.4.2, released 2019/06/28

Dear MAJA Developers and users. I have download Sentinel-2 L1C products using PEPS platform and peps_download.py. The period of images I have download is from 2019/08/01 to 2020/03/12 in (YYYY/MM/DD).

To process with MAJA, I am running the following script:

> python start_maja.py -f folders.txt -g GIPP/SENTINEL2_TM -l 20190626_LUT_MAJA_SENTINEL2_TM_NOCAMS/LUTs -t 16PDU -s CHINANDEGA -d 20190801 -e 202000312

It works fine, starting with backward mode and then changing to nominal mode. But when it finishes processing the last image of 2019 which is 2019/12/28, it just stop like if it was finished processing all the images and there is no error message. But no image for 2020 is processed. Below is a screenshot of the terminal:
![image](https://user-images.githubusercontent.com/6467913/78602738-3bdc4280-7857-11ea-9439-4deaccbff01f.png)

I tried it with 3 other tiles for the adjacent areas and it happens just the same.
Attached is the log file for the last image for one tile (16PDU).
[S2A_MSIL1C_20191228T161651_N0208_R140_T16PDU_20191228T194043.SAFE.log](https://github.com/CNES/Start-MAJA/files/4440698/S2A_MSIL1C_20191228T161651_N0208_R140_T16PDU_20191228T194043.SAFE.log)

What could be the problem?
Thanks for your help,

**Comment by olivierhagolle** [comment]
An easy one, try with end date:
-e 20200312
instead of 
-e 202000312

OK, I could have included a date verification in the parsing of parameters...
