### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by octoflar** [CNES/Start-MAJA#59]
Hi, when I run Start-MAJA using MAJA-3.3.5 [TM] I obtain the following error message:

    Traceback (most recent call last):
      File "./start_maja.py", line 661, in <module>
        start_maja(folder_file, gipp, lut, site, tile, orbit, nb_backward, options, debug_mode)
      File "./start_maja.py", line 561, in start_maja
        valid = test_valid_L2A(nomL2init_MUSCATE[0])
      File "./start_maja.py", line 216, in test_valid_L2A
        JPIfile = glob.glob("%s/DATA/*_JPI_ALL.xml" % L2A_DIR.replace('[', '[[]'))[0]
    IndexError: list index out of range

The error does not occur when I use MAJA-3.3.2 [TM].

**Comment by octoflar** [comment]
The issue occurred because the disk ran out of space. Sorry, please delete this issue.

**Comment by olivierhagolle** [comment]
No problem, thanks for letting us know.
