### ISSUE TITLE
maja for landsat product

### ISSUE THREAD

**Issue by smfcrts** [CNES/Start-MAJA#6]
hi,
i tested maja on sentinel products, and i'm wondering if does maja work on landsat8 products.

**Comment by olivierhagolle** [comment]
The answer is yes, but it is complicated

MAJA needs tiles as input. To enable multi-temporal processing, we need to have all the inputs to have the same upper left corner, projection, number of lines and columns... It is not the case with standard Landsat 8 products. Only the "ARD" products above US have this feature.

So, within Theia, we do a resampling and we tile the landsat products, but I have not introduced that in start_maja (I would love to, but it would mean one or two weeks of work). 

And USGS Landsat8 L2 have a good quality, i encourage you to  ask for them in https://earthexplorer.usgs.gov
Olivier

**Comment by smfcrts** [comment]
thank you for your answer
Just to better understand, you means that standard landsat 8 products should be processed to have the needed features to run start_maja.

**Comment by olivierhagolle** [comment]
yes, all Landsat 8 data within a time series for a given site should be cut into tiles, with exactly the same upper left corner location, and the same size. And of course there is a certain format to use.
Olivier

**Comment by smfcrts** [comment]
Thank you for your explanation.I hope you introduce that on start_maja as soon as possible.

**Comment by olivierhagolle** [comment]
I'll try, but certainly not before summer.
