### ISSUE TITLE
'srtm_49_08.tif' does not exist

### ISSUE THREAD

**Issue by lefebvre-antoine** [CNES/Start-MAJA#61]
Dear Olivier,
We found out a small issue when we create DTM for the tile 40RHN. It asks the 'srtm_49_08.tif' but this file does not exist. I checked and this tile should be somewhere in the sea over the Gulf of Oman... 
We deduce that there is an error in the data entry.
I hope this may help for future version...
Best regards, antoine

**Comment by ThomasCusson** [comment]
There seems to be a similar problem with srtm_35_05 and srtm_34_04

**Comment by olivierhagolle** [comment]
Thanks !
Yes, the CGIAR SRTM tiles are only available above lands. In my older version of start_maja, I had handled this issue for the water mask,  but it might have not been included in the new version. One more item in the list of things we should check, but we currently lack manpower.
Olivier

**Comment by olivierhagolle** [comment]
@ThomasCusson found the answer, the SRTM site is now a https site and not anymore a http,  and the address conversion does not work properly. We will adapt start-maja, but in case, you might do it alone:

Please change "StartMaja/prepare_mnt/mnt/SRTM.py, line 25" :
Replace
srtm_url = "http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/%s.zip"
by
srtm_url = "https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/%s.zip"

Thanks Thomas !
Olivier

**Comment by ThomasCusson** [comment]
@olivierhagolle The new https address solves a new problem that appeared, but not the original one for this issue.
