### ISSUE TITLE
Cannot find SWBD files

### ISSUE THREAD

**Issue by sac3g15** [CNES/Start-MAJA#62]
I am attempting to download DTM for study area via **DTMCreation-tool using the Sentinel2 tiling grid kml**

Command
python DTMCreation.py -k S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml -g 16QDE -s /noc/users/stcarp/Downloads/MAJA-3.3.5_TM/STRM/ -w /noc/users/stcarp/Downloads/MAJA-3.3.5_TM/SWBD/ -o /noc/users/stcarp/Downloads/MAJA-3.3.5_TM/DTM

Error
Found SRTM zip-archives...
Found Water zip-archives...
Processing with GranuleID
....
/tmp/16QDE4y6ecjrn
liste_fic_mnt ['srtm_40_30.tif']
Traceback (most recent call last):
  File "DTMCreation.py", line 326, in <module>
    creator.run(args.out, args.tempout)
  File "DTMCreation.py", line 286, in run
    water_zipped = self.WaterZipped)
  File "/noc/users/stcarp/Downloads/MAJA-3.3.5_TM/prepare_dtm/../prepare_dtm/tuilage_mnt_eau_S2.py", line 203, in run
    calcul_masque_eau_mnt, working_dir=working_dir)
  File "/noc/users/stcarp/Downloads/MAJA-3.3.5_TM/prepare_dtm/../prepare_dtm/lib_mnt.py", line 447, in fusion_mnt
    raise ValueError("Cannot find SWBD files!")
**ValueError: Cannot find SWBD files!**

Image of downloaded .zip from Earth Explorer
![Capture](https://user-images.githubusercontent.com/61827916/80993494-0feeb580-8e33-11ea-8d68-f628d76a7324.PNG)

Any ideas?

**Comment by sac3g15** [comment]
Required change in gdal..

**Comment by olivierhagolle** [comment]
Thanks for letting us know !
Olivier
