### ISSUE TITLE
Using other elevation models than SRTM

### ISSUE THREAD

**Issue by mazingaro** [CNES/Start-MAJA#64]
Hi, 

has anyone tried to use MAJA with other elevation models?
If not, do you think is it worth a try and what resolution do you think could be theoretically the best? (ex. 10 m)

Regards

**Comment by petket-5** [comment]
Hi,

I can confirm that the next version of Maja is going to implement the EuDEM v1.1, which will allow you to process the entirety of Europe :)

Feel free to suggest other formats if necessary!

Kind regards,
Peter

**Comment by mazingaro** [comment]
That sounds great! I was interested into trying a high-resolution DSM that
is calculated from governmental data (Slovenia). It starts from 1m and the
idea of trying a 10 and 30 m one within MAJA sounded intersting, but I
am/was not sure if I can just simply convert it to DTM (with the tool
stated here), tile it as SRTM tiles and use it directly.

**Comment by petket-5** [comment]
Hi,

Maja 4.2 just came online. With it you can use the EuDEM v1.1 data.

Kind regards,
Peter
