### ISSUE TITLE
About licence MAJA

### ISSUE THREAD

**Issue by adrycap** [CNES/Start-MAJA#67]
Hi, 
The Maja processor is currently open, Is there any plans to convert the system for a fee in the future?
or will it change the type of licence becoming restricted for commercial purposes?

Thank you very much, 

Adriana

**Comment by jerome-colin** [comment]
Dear Adriana,
Starting from the coming Maja 4.2 version, the processor will become open source (most probably by next September).
Best,
Jerome

**Comment by olivierhagolle** [comment]
Hi Adriana,
As @jerome-colin says, MAJA will be more open in the near future, not more restricted.
Olivier
