### ISSUE TITLE
What is this super big EEF file that makes MAJA crashes ?

### ISSUE THREAD

**Issue by lefebvre-antoine** [CNES/Start-MAJA#70]
Hi !

I noticed that MAJA produces 'sometimes' a very large EEF file (>1,2To!) in the GIPP_S2AS2B_XXX folder. 
I am wondering if this can be normal. Following this, the processing always crashes because I run out freespace ...
![image](https://user-images.githubusercontent.com/55259955/88852207-40ee4480-d1ee-11ea-808d-4e9c00eb99a8.png)

Thank you very much,
Best regards
antoine

**Comment by olivierhagolle** [comment]
Hi Antoine,
sorry for replying late. I think it is also related to the angle issue.
And I think @petket-5 knows about this bug ;)
Olivier

**Comment by petket-5** [comment]
I just updated the version of Maja to 4.2. You should no longer have this issue with it.

Peter

**Comment by lefebvre-antoine** [comment]
Oh great !
i gonna give it a try , thank you very much!
