### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by creffett** [CNES/Start-MAJA#87]
Hello,

I am a bit confused about the license situation of MAJA. The repository says that the code is Apache 2.0, but when I go to download the pre-compiled version from the CNES website (here)[https://logiciels.cnes.fr/en/license/58/649], I am presented with a very different license. I recognize that this is CNES's creation and they can license it however they wish, but the license on the pre-compiled version is very different from the license on the source code, and I am wondering if this is a mistake.

**Comment by olivierhagolle** [comment]
Yes you are right. CNES first released the pre-compiled version, then a couple of years later, released the code as open source. The license for the pre-compiled version should be removed from the logiciels.cnes.fr site and the Apache 2 licence is applicable.
Olivier

**Comment by creffett** [comment]
Perfect, that clears up all of my concerns. Thank you!
