### ISSUE TITLE
Maja creates L2A level data with empty cloud masks & 0 instead of -10000 for each band

### ISSUE THREAD

**Issue by atruffiercls** [CNES/Start-MAJA#99]
Hello, 

I work for CLS and in the context of classification processing, I produce L2A_MAJA with the help of MAJA 4.5.2. 
I saw that, for data after the 25th of january, the L2A MAJAs produced had two differences with the L2A MAJAs produced before this date : 
- The Cloud Masks produced are empty
- The bands have a nodata set at 0 instead of -10000 
I might be doing somehting wrong. I looked for a parameter that could help MAJA to produce L2As with the same caracteristics, but the only solution I found today is changing with a script the 0 to -10000 and create the two masks according to the new -10000 areas.

Hope this issue had not been signaled yet. 

Thank you for your help, 
Have a nice day ! 

Amaury Truffier

**Comment by jerome-colin** [comment]
Dear Amaury,
Thank you for your message. I just opened an issue on our GitLab repository, you'll be able to keep track of it here : 
https://gitlab.orfeo-toolbox.org/maja/maja/-/issues/302

Github is not the main development repository, although we keep pushing new releases here. 

Jerome

**Comment by jerome-colin** [comment]
Please also note that we published a patch, and I'd recommend you move to 4.5.3

**Comment by jerome-colin** [comment]
Dear Amaury,
I just got the confirmation from the dev team that this issue is fixed in 4.5.3.
Best regards,
Jerome

**Comment by atruffiercls** [comment]
Hello, 

Thank you very much for this fast answer ! 
I will try with this new version.

Best regards, 

Amaury
